<?php

/**
 * Indicatifs téléphoniques (E.164 sans le +) par code ISO 3166-1 alpha-2.
 * Libellés en anglais pour le sélecteur d’inscription (liste triée côté contrôleur).
 *
 * @var array<string, array{dial: string, name: string}>
 */
return [
    'MA' => ['dial' => '212', 'name' => 'Morocco'],
    'DZ' => ['dial' => '213', 'name' => 'Algeria'],
    'TN' => ['dial' => '216', 'name' => 'Tunisia'],
    'LY' => ['dial' => '218', 'name' => 'Libya'],
    'MR' => ['dial' => '222', 'name' => 'Mauritania'],
    'FR' => ['dial' => '33', 'name' => 'France'],
    'BE' => ['dial' => '32', 'name' => 'Belgium'],
    'CH' => ['dial' => '41', 'name' => 'Switzerland'],
    'DE' => ['dial' => '49', 'name' => 'Germany'],
    'IT' => ['dial' => '39', 'name' => 'Italy'],
    'ES' => ['dial' => '34', 'name' => 'Spain'],
    'PT' => ['dial' => '351', 'name' => 'Portugal'],
    'NL' => ['dial' => '31', 'name' => 'Netherlands'],
    'LU' => ['dial' => '352', 'name' => 'Luxembourg'],
    'GB' => ['dial' => '44', 'name' => 'United Kingdom'],
    'IE' => ['dial' => '353', 'name' => 'Ireland'],
    'US' => ['dial' => '1', 'name' => 'United States'],
    'CA' => ['dial' => '1', 'name' => 'Canada'],
    'AE' => ['dial' => '971', 'name' => 'United Arab Emirates'],
    'SA' => ['dial' => '966', 'name' => 'Saudi Arabia'],
    'EG' => ['dial' => '20', 'name' => 'Egypt'],
    'QA' => ['dial' => '974', 'name' => 'Qatar'],
    'KW' => ['dial' => '965', 'name' => 'Kuwait'],
    'BH' => ['dial' => '973', 'name' => 'Bahrain'],
    'OM' => ['dial' => '968', 'name' => 'Oman'],
    'JO' => ['dial' => '962', 'name' => 'Jordan'],
    'LB' => ['dial' => '961', 'name' => 'Lebanon'],
    'SY' => ['dial' => '963', 'name' => 'Syria'],
    'IQ' => ['dial' => '964', 'name' => 'Iraq'],
    'YE' => ['dial' => '967', 'name' => 'Yemen'],
    'PS' => ['dial' => '970', 'name' => 'Palestine'],
    'IL' => ['dial' => '972', 'name' => 'Israel'],
    'TR' => ['dial' => '90', 'name' => 'Turkey'],
    'IN' => ['dial' => '91', 'name' => 'India'],
    'CN' => ['dial' => '86', 'name' => 'China'],
    'JP' => ['dial' => '81', 'name' => 'Japan'],
    'KR' => ['dial' => '82', 'name' => 'South Korea'],
    'PK' => ['dial' => '92', 'name' => 'Pakistan'],
    'BD' => ['dial' => '880', 'name' => 'Bangladesh'],
    'ID' => ['dial' => '62', 'name' => 'Indonesia'],
    'MY' => ['dial' => '60', 'name' => 'Malaysia'],
    'SG' => ['dial' => '65', 'name' => 'Singapore'],
    'TH' => ['dial' => '66', 'name' => 'Thailand'],
    'VN' => ['dial' => '84', 'name' => 'Vietnam'],
    'PH' => ['dial' => '63', 'name' => 'Philippines'],
    'AU' => ['dial' => '61', 'name' => 'Australia'],
    'NZ' => ['dial' => '64', 'name' => 'New Zealand'],
    'ZA' => ['dial' => '27', 'name' => 'South Africa'],
    'NG' => ['dial' => '234', 'name' => 'Nigeria'],
    'KE' => ['dial' => '254', 'name' => 'Kenya'],
    'GH' => ['dial' => '233', 'name' => 'Ghana'],
    'SN' => ['dial' => '221', 'name' => 'Senegal'],
    'CI' => ['dial' => '225', 'name' => "Côte d'Ivoire"],
    'CM' => ['dial' => '237', 'name' => 'Cameroon'],
    'BR' => ['dial' => '55', 'name' => 'Brazil'],
    'MX' => ['dial' => '52', 'name' => 'Mexico'],
    'AR' => ['dial' => '54', 'name' => 'Argentina'],
    'CL' => ['dial' => '56', 'name' => 'Chile'],
    'CO' => ['dial' => '57', 'name' => 'Colombia'],
    'RU' => ['dial' => '7', 'name' => 'Russia'],
    'UA' => ['dial' => '380', 'name' => 'Ukraine'],
    'PL' => ['dial' => '48', 'name' => 'Poland'],
    'RO' => ['dial' => '40', 'name' => 'Romania'],
    'CZ' => ['dial' => '420', 'name' => 'Czechia'],
    'AT' => ['dial' => '43', 'name' => 'Austria'],
    'SE' => ['dial' => '46', 'name' => 'Sweden'],
    'NO' => ['dial' => '47', 'name' => 'Norway'],
    'DK' => ['dial' => '45', 'name' => 'Denmark'],
    'FI' => ['dial' => '358', 'name' => 'Finland'],
    'GR' => ['dial' => '30', 'name' => 'Greece'],
    'CY' => ['dial' => '357', 'name' => 'Cyprus'],
    'MT' => ['dial' => '356', 'name' => 'Malta'],
    'IS' => ['dial' => '354', 'name' => 'Iceland'],
    'HU' => ['dial' => '36', 'name' => 'Hungary'],
    'SK' => ['dial' => '421', 'name' => 'Slovakia'],
    'SI' => ['dial' => '386', 'name' => 'Slovenia'],
    'HR' => ['dial' => '385', 'name' => 'Croatia'],
    'RS' => ['dial' => '381', 'name' => 'Serbia'],
    'BA' => ['dial' => '387', 'name' => 'Bosnia and Herzegovina'],
    'BG' => ['dial' => '359', 'name' => 'Bulgaria'],
    'AL' => ['dial' => '355', 'name' => 'Albania'],
    'MK' => ['dial' => '389', 'name' => 'North Macedonia'],
    'MD' => ['dial' => '373', 'name' => 'Moldova'],
    'GE' => ['dial' => '995', 'name' => 'Georgia'],
    'AM' => ['dial' => '374', 'name' => 'Armenia'],
    'AZ' => ['dial' => '994', 'name' => 'Azerbaijan'],
    'KZ' => ['dial' => '7', 'name' => 'Kazakhstan'],
    'UZ' => ['dial' => '998', 'name' => 'Uzbekistan'],
    'TM' => ['dial' => '993', 'name' => 'Turkmenistan'],
    'TJ' => ['dial' => '992', 'name' => 'Tajikistan'],
    'KG' => ['dial' => '996', 'name' => 'Kyrgyzstan'],
    'AF' => ['dial' => '93', 'name' => 'Afghanistan'],
    'LK' => ['dial' => '94', 'name' => 'Sri Lanka'],
    'NP' => ['dial' => '977', 'name' => 'Nepal'],
    'IR' => ['dial' => '98', 'name' => 'Iran'],
    'ET' => ['dial' => '251', 'name' => 'Ethiopia'],
    'SD' => ['dial' => '249', 'name' => 'Sudan'],
    'SO' => ['dial' => '252', 'name' => 'Somalia'],
    'TZ' => ['dial' => '255', 'name' => 'Tanzania'],
    'UG' => ['dial' => '256', 'name' => 'Uganda'],
    'RW' => ['dial' => '250', 'name' => 'Rwanda'],
    'MG' => ['dial' => '261', 'name' => 'Madagascar'],
    'MU' => ['dial' => '230', 'name' => 'Mauritius'],
    'ZW' => ['dial' => '263', 'name' => 'Zimbabwe'],
    'BW' => ['dial' => '267', 'name' => 'Botswana'],
    'NA' => ['dial' => '264', 'name' => 'Namibia'],
    'MZ' => ['dial' => '258', 'name' => 'Mozambique'],
    'AO' => ['dial' => '244', 'name' => 'Angola'],
    'CD' => ['dial' => '243', 'name' => 'DR Congo'],
    'CG' => ['dial' => '242', 'name' => 'Congo'],
    'GA' => ['dial' => '241', 'name' => 'Gabon'],
    'BF' => ['dial' => '226', 'name' => 'Burkina Faso'],
    'ML' => ['dial' => '223', 'name' => 'Mali'],
    'NE' => ['dial' => '227', 'name' => 'Niger'],
    'BJ' => ['dial' => '229', 'name' => 'Benin'],
    'TG' => ['dial' => '228', 'name' => 'Togo'],
    'LR' => ['dial' => '231', 'name' => 'Liberia'],
    'SL' => ['dial' => '232', 'name' => 'Sierra Leone'],
    'GM' => ['dial' => '220', 'name' => 'Gambia'],
    'GN' => ['dial' => '224', 'name' => 'Guinea'],
    'GW' => ['dial' => '245', 'name' => 'Guinea-Bissau'],
    'VE' => ['dial' => '58', 'name' => 'Venezuela'],
    'PE' => ['dial' => '51', 'name' => 'Peru'],
    'EC' => ['dial' => '593', 'name' => 'Ecuador'],
    'UY' => ['dial' => '598', 'name' => 'Uruguay'],
    'PY' => ['dial' => '595', 'name' => 'Paraguay'],
    'BO' => ['dial' => '591', 'name' => 'Bolivia'],
    'CR' => ['dial' => '506', 'name' => 'Costa Rica'],
    'PA' => ['dial' => '507', 'name' => 'Panama'],
    'GT' => ['dial' => '502', 'name' => 'Guatemala'],
    'HN' => ['dial' => '504', 'name' => 'Honduras'],
    'SV' => ['dial' => '503', 'name' => 'El Salvador'],
    'NI' => ['dial' => '505', 'name' => 'Nicaragua'],
    'DO' => ['dial' => '1', 'name' => 'Dominican Republic'],
    'JM' => ['dial' => '1', 'name' => 'Jamaica'],
    'TT' => ['dial' => '1', 'name' => 'Trinidad and Tobago'],
    'HK' => ['dial' => '852', 'name' => 'Hong Kong'],
    'TW' => ['dial' => '886', 'name' => 'Taiwan'],
    'MO' => ['dial' => '853', 'name' => 'Macao'],
];
