<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ __('Sourcing Orders Report') }}</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            color: #333;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 9px;
            color: #999;
            padding: 10px 0;
            border-top: 1px solid #eee;
        }
        .status-badge {
            padding: 2px 4px;
            border-radius: 3px;
            font-size: 8px;
            text-transform: uppercase;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ __('Full Sourcing Orders Report') }}</h1>
        <p>{{ __('Export Date:') }} {{ date('d/m/Y H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>{{ __('ID') }}</th>
                <th>{{ __('Product') }}</th>
                <th>{{ __('Client') }}</th>
                <th>{{ __('Total Quantity') }}</th>
                <th>{{ __('Total Amount') }}</th>
                <th>{{ __('Status') }}</th>
                <th>{{ __('Assigned to') }}</th>
                <th>{{ __('Creation Date') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sourcingOrders as $order)
                <tr>
                    <td>#{{ $order->display_id }}</td>
                    <td>
                        {{ $order->quotation->sourcingRequest->product_name ?? 'N/A' }}
                    </td>
                    <td>
                        {{ $order->user->name }}<br>
                        <small>{{ $order->user->email }}</small>
                    </td>
                    <td>
                        {{ $order->quotation->sourcingRequest->destinations->sum('quantity') }}
                    </td>
                    <td>{{ number_format($order->total_amount, 2) }} {{ $order->quotation->currency }}</td>
                    <td>
                        {{ ucfirst(str_replace('_', ' ', $order->status)) }}
                    </td>
                    <td>{{ $order->assignedAdmin->name ?? __('Unassigned') }}</td>
                    <td>{{ $order->created_at->format('d/m/Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ __('Generated by Sourcing App - Page') }} <script type="text/php">if (isset($pdf)) { echo $pdf->get_page_number(); }</script>
    </div>
</body>
</html>
